#!/bin/bash

set -e

try() {
    RUBY=$1 ./test >&2
    $1 -v
}

pick() {
    if which $1 >/dev/null
    then try $1
    else try $HOME/.rbenv/versions/$1/bin/ruby
    fi
}

{
    echo -n "This commit was tested "
    date
    echo using the following ruby interpreters:

    if test $# -lt 1
    then vs=`ls $HOME/.rbenv/versions`
    else vs=$*
    fi

    for r in $vs
    do pick $r
    done
} >tested-on
