#!/bin/bash

set -e

: ${RUBY:=ruby}

enc() {
    $RUBY -r ./okjson -e 'puts(OkJson.encode(eval($stdin.read)))'
}

cycle() {
    $RUBY -r ./okjson -e 'puts(OkJson.encode(OkJson.decode($stdin.read)))'
}

fs=$*
if test -z "$fs"
then fs=`echo t/*.{json,rb}`
fi

trap 'echo $RUBY; echo $f' EXIT
for f in $fs
do
    case $f in
    t/valid*.json)
        cycle <$f >/dev/null
        diff $f.exp <(cycle <$f 2>/dev/null)
        ;;
    t/invalid*.json)
        if cycle <$f 2>/dev/null
        then echo; exit 1
        fi
        ;;
    t/encode*.rb)
        enc <$f >/dev/null
        diff $f.exp <(enc <$f 2>/dev/null)
        ;;
    t/err*.rb)
        if enc <$f 2>/dev/null
        then echo >&2 expected error; exit 1
        fi
        ;;
    esac
done
trap - EXIT
